# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0fb681077e3da21d2ac1a326d9d1776ee003c2c515c71c6580434941bb5a29f7b261b313d10babe6747d541eea2236124cf50a16395dd668463d9760a3b8ade4

test:
  secret_key_base: 016c938c50c93bd35cb6931b3beb07fd1355fad23d79d722e9383a6a3e6b15f8f65edffb8f0e94f84a863ddd9c95d3ddc6568c7b15d56870f9c9cd554c9d50bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
